### ISSUE TITLE
Support for Rector 0.17.3

### ISSUE THREAD

**Issue by driftingly** [driftingly/rector-laravel#120]
It looks like Rector is moving away from BetterNodeFinder.
Lots of deprecated methods: https://github.com/rectorphp/rector/issues/7947

We'll need to update calls to `$this->betterNodeFinder->*`.

**Comment by GeniJaho** [comment]
Do you have any suggestions about finding parents of classes? With BetterNodeFinder it was a one-liner but now we have to rely on reflection, which adds a few extra lines and cases to think about. I'm working on updating the rules dependent on BetterNodeFinder but not sure if there's a better way.

Also not sure if there are any performance penalties if we use AbstractScopeAwareRector instead of AbstractRector 👀.

**Comment by driftingly** [comment]
Thanks for all your work on this @GeniJaho 🙌
