### ISSUE TITLE
Incompatible with Rector v0.17

### ISSUE THREAD

**Issue by freshleafmedia** [driftingly/rector-laravel#121]
[Rector v0.17.0](https://github.com/rectorphp/rector/releases/tag/0.17.0) and above aren't compatible. It appears to be due to things like the `findParentType` method and `nodesToAddCollector` property being removed.

I'm using rector-laravel v0.21.0

**Comment by gisostallenberg** [comment]
`composer.json` should contain the required rector version.

I run driftingly/rector-laravel v0.21.0 which works fine on rector 0.17.2 but not on 0.17.3, because in that version BetterNodeFinder::findParentType was removed, see https://github.com/rectorphp/rector/releases/tag/0.17.3

According to [SemVer](https://semver.org/#spec-item-4) rector can do breaking changes, but I think it should have a new minor version (0.18.0).

**Comment by driftingly** [comment]
@gisostallenberg @freshleafmedia Just released the updates by @GeniJaho, which should resolve this issue.  Let me know.

**Comment by gisostallenberg** [comment]
@driftingly you mean the changes in https://github.com/driftingly/rector-laravel/pull/117?

**Comment by driftingly** [comment]
Yeah. I tried on a fresh install and latest Rector and it ran. Noticed there are some failing test though with everything merged in.

**Comment by driftingly** [comment]
And it looks like we are green again 🙌
