### ISSUE TITLE
Incorrect packagist requirements

### ISSUE THREAD

**Issue by CornerMonkey** [driftingly/rector-laravel#150]
The packagist requirements for this repo do not align with the composer.json.  

On packagist for the latest version (https://packagist.org/packages/driftingly/rector-laravel#0.26.2), the requirements are: 

- php: ^7.2 || ^8.0

However, the repo, has: 
- php: ">=8.1
- rector/rector: ^0.18.0

This causes issues for composer updates/new installs because it is installing the latest version, even when running older versions of `PHP` and `Rector`.

**Comment by chris-ware** [comment]
Shouldn't the requirement for rector always be included, even if the PHP version support is dropped for some reason? The fact that it isn't included means that it has to be manually required, which means maintaining it separately and then trying to figure out why stuff is broken, because support has been moved to the next 0.* release of rector.

**Comment by driftingly** [comment]
@CornerMonkey @chris-ware Sorry, yes, that makes sense.  Since Rector is also downgraded we will be able to require the same version in both the source and downgraded.  I'll update the downgraded `composer.json` to include Rector.

**Comment by driftingly** [comment]
Can you try [0.28.1](https://github.com/driftingly/rector-laravel/releases/tag/0.28.1) and let me know if this fixes the issue?

https://packagist.org/packages/driftingly/rector-laravel
