### ISSUE TITLE
laravel54 every => nth breaks modern use of Collection::every

### ISSUE THREAD

**Issue by hackel** [driftingly/rector-laravel#186]
On my Laravel 10 project, I've enabled the `LaravelLevelSetList::UP_TO_LARAVEL_100` set.  (Please tell me if that's not the right way to use this package.)

In the laravel54 rules, it renames uses of `Collection::every` to `Collection::nth`.  I'm sure this was appropriate for Laravel 5.4, but Collection has since added a new `every` method which is completely different from the `nth` method.  I have had to disable the set in the meantime.

**Comment by driftingly** [comment]
Thanks for reporting.

The [Laravel 5.4 rules](https://github.com/driftingly/rector-laravel/blob/68a890f1720caf4d112ce9928404261d07fe7e11/config/sets/laravel54.php#L35) follow the [Laravel 5.4 upgrade guide](https://laravel.com/docs/5.4/upgrade):

>The every Method
>The behavior of the every method has been moved to the nth method to match the method name defined by Lodash.

This is not what you want on a Laravel 10 app.

I'm sure there are/will be more instances of conflicting rules designed for older versions of Laravel.  

We'll have to figure out ways of checking current versions, or maybe deprecating some of the older rules for the newer sets. 

Since this particular rule is only valid when upgrading from 5.3 to 5.4 it can be dropped from the rule set.
