### ISSUE TITLE
Conversion of TrustProxies for Laravel 9

### ISSUE THREAD

**Issue by jeff1326** [driftingly/rector-laravel#216]
app/Http/Middleware/TrustProxies.php is not converted

See https://laravel.com/docs/9.x/upgrade#the-assert-deleted-method

**Comment by peterfox** [comment]
Sorry, I'm confused here @jeff1326. You linked to the assert deleted method but mentioned the TrustProxies?

I think we've liked left TrustProxies out of the upgrade because of a couple reasons:
- it's a single file update, meaning writing a rule, and the test for it has a limited return on investment compared to recommending a manual upgrade.
- it's also required along with a composer package change which Rector doesn't/can't handle. Meaning that this will always have a level of manual intervention anyways.
