### ISSUE TITLE
Erroneous conversion of Validator in UP_TO_LARAVEL_110

### ISSUE THREAD

**Issue by ayrtonandino** [driftingly/rector-laravel#272]
I have a custom rule that implements `Illuminate\Contracts\Validation\ValidatorAwareRule`, if rector is run with set `LaravelLevelSetList::UP_TO_LARAVEL_110` it changes the $validator from the correct `Illuminate\Validation\Validator` class to `Illuminate\Contracts\Validation\Validator` interface.

```zsh
1) app/Rules/StartsWithRule.php:9

    ---------- begin diff ----------
@@ @@

 class StartsWithRule implements ValidationRule, ValidatorAwareRule
 {
-    protected Validator $validator;
+    protected \Illuminate\Contracts\Validation\Validator $validator;

-    public function setValidator(Validator $validator): static
+    public function setValidator(\Illuminate\Contracts\Validation\Validator $validator): static
     {
         $this->validator = $validator;
    ----------- end diff -----------

Applied rules:
 * MinutesToSecondsInCacheRector
 * RenameClassRector
 * StringToClassConstantRector
```

this change comes from `LARAVEL_51` rule set as per [Laravel 5.1 upgrade documentation](https://laravel.com/docs/5.1/upgrade):

> # Validation
>
> If you are overriding the `formatValidationErrors` method on your base controller class, you should now type-hint the `Illuminate\Contracts\Validation\Validator` contract instead of the concrete `Illuminate\Validation\Validator` instance.
>
> Likewise, if you are overriding the `formatErrors` method on the base form request class, you should now type-hint `Illuminate\Contracts\Validation\Validator` contract instead of the concrete `Illuminate\Validation\Validator` instance.

**Comment by GeniJaho** [comment]
@ayrtonandino what is the issue here?
Keep in mind that when using the `LaravelLevelSetList::UP_TO_LARAVEL_*` sets, Rector will run all the previous version rules. In your case the 5.1 rules are run and change the code accordingly.

If you want to run only rules from the Laravel 11 set, use `LaravelSetList::LARAVEL_110` instead.

**Comment by ayrtonandino** [comment]
Agree, is working as expected, but, what's the point of that set then?

I ran it just to know if there was something i miss in the years of upgrading my app from 7 to 11, only thing was that change, that is wrong for Laravel 8 onwards as `ValidatorAwareRule` interface was introduced in 8.

So, if someone whats to go from 8+ to newest version, and has a rule implementing `ValidatorAwareRule`, it will get that modification because of a 10 years old laravel version.

I see 2 ways of fixing this, either by removing the `UP_TO_LARAVEL_*`, or by having `LARAVEL_51` only change `Validator` where it was actually intended:
- in the `base controller class`, that was overriding `formatValidationErrors` method 
- in the `base form request class`, that was overriding `formatErrors` method.

**Comment by peterfox** [comment]
I'm not 100% sure on the issue @ayrtonandino so I have a question.

Is the problem that essentially the rule is rewriting a method's signature because it's trying to use the contract when the method is from another contract (`ValidatorAwareRule`), therefore breaking the implementing class?

Could you share a copy of your Rector config and the file in question if possible, please?

**Comment by ayrtonandino** [comment]
Hi, thanks for taking the time to see this, I made a small reproduction so you can see what i mean.

I used Laravel 11, but this apply to any Laravel 8+ using `UP_TO_LARAVEL_*`

#### Steps to reproduce

1. Clone Git repo
```bash
git clone https://github.com/ayrtonandino/up-to-laravel-bug.git
```

2. cd into it and run Run composer install command
```bash
cd up-to-laravel-bug && composer install
```

3. run composer test command
```bash
composer test
```

> [!NOTE]
> `composer test` will first run `composer stan` and you will get no errors.
>
> Then it will run `composer rector` to apply rector changes, modifing `StartsWithRule.php`.
>
> Finally it will run `composer stan` again, now showing error `Call to an undefined method Illuminate\Contracts\Validation\Validator::getData()` introduced by `LARAVEL_51`

### rector config used in reproduction
```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use RectorLaravel\Set\LaravelLevelSetList;

return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/rector.php',
        __DIR__ . '/app',
        __DIR__ . '/bootstrap',
        __DIR__ . '/config',
        __DIR__ . '/database',
        __DIR__ . '/public/index.php',
        __DIR__ . '/resources/views',
        __DIR__ . '/routes',
        __DIR__ . '/tests',
    ])
    ->withSets([
        LaravelLevelSetList::UP_TO_LARAVEL_110,
    ]);
```


### phpstan config used in reproduction
```neon
includes:
    - vendor/larastan/larastan/extension.neon
    - vendor/nesbot/carbon/extension.neon

parameters:

    paths:
        - app/

    level: 10
```

**Comment by peterfox** [comment]
@ayrtonandino if the only problem is because PHPStan is unhappy with the use of the contract, one way to fix this is to use doc block comments to specify the type.

If you use the file as follows, it should fix your problem and PHPStan will pass without fighting with Rector.

```php
<?php

namespace App\Rules;

use Closure;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Contracts\Validation\ValidatorAwareRule;
use Illuminate\Translation\PotentiallyTranslatedString;
use Illuminate\Validation\Validator;
use Override;

class StartsWithRule implements ValidationRule, ValidatorAwareRule
{
    /**
     * @var \Illuminate\Validation\Validator
     */
    protected \Illuminate\Contracts\Validation\Validator $validator;

    #[Override]
    /**
     * @param \Illuminate\Validation\Validator $validator
     */
    public function setValidator(\Illuminate\Contracts\Validation\Validator $validator): static
    {
        $this->validator = $validator;

        return $this;
    }

    /**
     * Run the validation rule.
     *
     * @param  Closure(string, ?string=):PotentiallyTranslatedString  $fail
     */
    #[Override]
    public function validate(string $attribute, mixed $value, Closure $fail): void
    {
        // Call to an undefined method Illuminate\Contracts\Validation\Validator::getData().
        $this->validator->getData();
    }
}
```

The problem itself originates with the [RenameClassRector](https://getrector.com/rule-detail/rename-class-rector) that isn't recognising that the implementation is set from an overriding method. I'm not sure in PHP land what the best outcome of this would be, to keep the implementation or to use the interface. Clearly PHP allows it.

For now this would be incredible hard to change for us alone as the rule isn't maintained by this project, only used by it. For now I suggest using the suggested fix to get PHPStan to pass.
